
jobs:
  include:
  - os: linux
    dist: bionic
    name: Linux E+ Tests
    language: python
    python: 3.6
    before_script: pip3 install -r requirements.txt
    script: python3 setup.py run
  - os: osx
    name: Mac E+ Tests
    osx_image: xcode11.4
    before_script: pip3 install -r requirements.txt
    script: python3 setup.py run
  - os: windows
    language: cpp  # just for fun?
    name: Windows E+ Tests
    before_script:
      - choco install python --version 3.6.8
      - pip3 install -r requirements.txt
    script: python setup.py run
    env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
  - os: linux
    dist: bionic
    name: Flake8
    language: python
    python: 3.6
    before_script: pip3 install -r requirements.txt
    script: python3 setup.py flake8
