
os: linux  # just a default OS, will be overridden in jobs list
dist: bionic


jobs:
  include:
  - os: linux
    name: Linux E+ Tests
    python: 3.6
    before_script: pip3 install -r requirements.txt
    script: python3 setup.py run
  - os: osx
    name: Mac E+ Tests
    osx_image: xcode11.2
    before_script: pip3 install -r requirements.txt
    script: python3 setup.py run
  - os: windows
    name: Windows E+ Tests
    install: choco install python3
    before_script: pip3 install -r requirements.txt
    script: python3 setup.py run