name: BuildAndTest
on: push
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
#          - os: ubuntu-20.04
#            key: ubuntu2004
#          - os: ubuntu-22.04
#            key: ubuntu2204
          - os: macos-11
            key: mac11
          - os: macos-12
            key: mac12
#          - os: windows-2019
#            key: win64
#          - os: windows-2019  -- GitHub Action image doesn't have 32-bit compiler by default, remove 32-bit soon, ok?
#            key: win32
#          - os: windows-2022
#            key: win64-2022server
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: pip3 install -r requirements.txt
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - name: Run Tests
        run: python3 setup.py run --run-config ${{ matrix.key }}
