name: BuildAndTest
on: push
jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            key: ubuntu1804
          - os: ubuntu-20.04
            key: ubuntu2004
          - os: macos-10.15
            key: mac1015
          - os: macos-11
            key: mac11
          - os: windows-2019
            key: win64
#          - os: windows-2019  -- GitHub Action image doesn't have 32-bit compiler by default, remove 32-bit soon, ok?
#            key: win32
#          - os: windows-2022  -- just need to add this sometime
#            key: win64
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install Dependencies
        run: pip3 install -r requirements.txt
      - name: Run Tests
        run: python3 setup.py run --run-config ${{ matrix.key }}
